### ISSUE TITLE
Tween `ResMut` resources

### ISSUE THREAD

**Issue by musjj** [djeedai/bevy_tweening#102]
Is there a way to use resources (`ResMut`) as a target for the tween? Would open up a lot of nice possibilities.

**Comment by djeedai** [comment]
https://docs.rs/bevy_tweening/latest/bevy_tweening/struct.AssetAnimator.html

**Comment by musjj** [comment]
Right, but that's specifically for `Asset`. What I wanted to do is to mutate arbitrary resources. Is there a way to do this?

**Comment by djeedai** [comment]
No it's not possible. Technically it requires a separate system because you can't mix components and resources. And from a design perspective I don't really see the point, that would mean running an entire system for a single object, this defeats the very purpose of an ECS engine.

**Comment by musjj** [comment]
I see. What I wanted to do is to slow down the `ResMut<Time>` using `time.set_relative_speed` and slowly increase it back up. I guess I can just make my own system for this, but I was hoping that I could re-use this library for its easing functions.

**Comment by djeedai** [comment]
The easing functions are from an external dependency, not from this library.

**Comment by musjj** [comment]
Thanks for the info, I used the `interpolation` library directly and it's working pretty well.

**Comment by djeedai** [comment]
Cool! Glad that worked
