### ISSUE TITLE
The 'custom component' description is misleading

### ISSUE THREAD

**Issue by SecretPocketCat** [djeedai/bevy_tweening#103]
As [noted on discord](https://discord.com/channels/691052431525675048/1036006196659900497/1162847997089021973), the the `custom component` part of the readme is a bit misleading and a common source of confusion. The readme should probably be more explicit about the fact that not all built-in components are supported (and probably just link to the plugin source as both an example of adding the system and to show which types are added by default).

**Comment by djeedai** [comment]
Fixed, thanks!
