### ISSUE TITLE
Bevy 0.13

### ISSUE THREAD

**Issue by asour8** [djeedai/bevy_tweening#118]
Bevy 0.13
![image](https://github.com/djeedai/bevy_tweening/assets/52638772/81481012-eacd-4ad2-ac36-ba2f37b98cd6)

**Comment by andrewexton373** [comment]
Is there a problem supporting bevy 0.13? I noticed there were already a couple PRs for 0.13 support #119 and #117, however they're not passing a few checks. Provided these checks passed, would you consider 0.13 support? Just checking as this was marked as not planned and I'd like to continue using this bevy plugin in up-to-date projects.

**Comment by djeedai** [comment]
I'm waiting for one of the authors to fix their PRs. This issue was closed for other reasons (the author opened a bunch of those issues in various Bevy related repositories without any comment or explanation, so I auto closed all of them in my repos).

**Comment by andrewexton373** [comment]
Ah understandable. Yeah I saw that in a few other repos as well, I
appreciate the update!
