### ISSUE TITLE
x11 feature

### ISSUE THREAD

**Issue by extrawurst** [djeedai/bevy_tweening#140]
is it possible to allow the user of `bevy_tweening` to optionally enable `x11` only if needed?

**Comment by djeedai** [comment]
Do you need Wayland?

**Comment by extrawurst** [comment]
not if i compile on windows, mac or wasm

**Comment by djeedai** [comment]
But this shouldn't have any effect on those platforms, hopefully? Otherwise
that sounds like a Bevy bug, no?

**Comment by djeedai** [comment]
But this shouldn't have any effect on those platforms, hopefully? Otherwise that sounds like a Bevy bug, no?

**Comment by extrawurst** [comment]
It’s mostly about wasm not building in code that increases the wasm size but is not needed

**Comment by djeedai** [comment]
Ok thanks. Yes we can add a feature or something to make it conditional on Linux, I'll have a look when I have a minute (or someone else can propose a change).

**Comment by djeedai** [comment]
Closing as per discussion on #141, the feature has no effect outside Linux.
