### ISSUE TITLE
Translation values still being changed after Animation played "Once" finished

### ISSUE THREAD

**Issue by jakyle** [djeedai/bevy_tweening#33]
Whenever I use the TransformPositionLens with TweeningType::Once, even after the animation is completed, the entitities transform seems to be "changed" still.  I know this because I have another system listening on transform Change and it is triggering every frame.

```rust
#[derive(Component)]
pub struct ImTweeningHere;

pub fn move_player_on_click(
    mut commands: Commands,
    mouse_input: Res<Input<MouseButton>>,
    grid_dimensions: Res<GridDimensions>,
    mouse_map_pos: Option<Res<MouseMapPos>>,
    player: Query<(Entity, &Transform), (With<Player>, Without<ImTweeningHere>)>,
) {
    if let (true, Some(mouse_map_pos)) = (
        mouse_input.just_pressed(MouseButton::Left),
        mouse_map_pos.as_deref(),
    ) {
        if let Ok((entity, player_transform)) = player.get_single() {
            let end_position = grid_dimensions.grid_loc_to_vec2(
                (mouse_map_pos.0.x / grid_dimensions.tile_area).floor(),
                (mouse_map_pos.0.y / grid_dimensions.tile_area).floor(),
            );

            let tween = Tween::new(
                EaseFunction::CircularInOut,
                TweeningType::Once,
                std::time::Duration::from_millis(500),
                TransformPositionLens {
                    start: player_transform.translation,
                    end: Transform::from_translation(end_position.extend(player_transform.translation.z))
                        .translation,
                },
            )
            .with_completed_event(true, 0);

            let animator = Animator::new(tween);
            commands
                .entity(entity)
                .insert(animator)
                .insert(ImTweeningHere);
        }
    }
}
```

the above system triggers the animation on map click, when the animation completes, the entities Transform still fires off 

```rust
fn player_transforming(
    player: Query<&Transform, (With<Player>, Changed<Transform>)>,
) {
    if let Ok(transforming) = player.get_single() {
        info!("player is transforming!: {transforming:?}");
    }
}
```

as a work around, I manually remove the AnimatorTransform on tween complete

```rust
fn movement_completed(mut commands: Commands, mut on_tween_complete: EventReader<TweenCompleted>) {
    for evt in on_tween_complete.iter() {
        if evt.user_data == 0 {
            commands
                .entity(evt.entity)
                .remove::<ImTweeningHere>()
                .remove::<Animator<Transform>>();
        }
    }
}
```

However, I am not sure if this is the intended behavior.  do we need to remove the Animator on animation complete. I expect that the intended behavior when using a TweeningType of Once is the component will be removed on animation complete for the entity and we use the TweenCompleted event for other stuff, like my use case here to remove my own component.

**Comment by djeedai** [comment]
I tried to fix, this needs a Bevy change to be fixed cleanly. The change went in already (bevyengine/bevy#5438) so this can be fixed in next version when we upgrade to Bevy 0.8 (which is imminent).

**Comment by jakyle** [comment]
great, thanks for the reply :) and thanks for looking into this

**Comment by djeedai** [comment]
@jakyle sorry for the delay, that took a while. Bevy 0.8 did fix what I needed, but also introduced other blockers for this issue, so I had to get help from the ECS team to figure out how to fix and test this. Change detection should work as expected now, and I've added a test for components, but feel free to reopen if there's still an issue.
