### ISSUE TITLE
menu example panics with `can not convert float seconds to Duration: value is negative`

### ISSUE THREAD

**Issue by djeedai** [djeedai/bevy_tweening#41]
@Gyrobifastigium FYI this is probably a bug in #39

This is blocking #34

**Comment by Gyrobifastigium** [comment]
The panic happens because:

- The `Delay` tween in the example has a 0-duration `self.timer`, so `self.timer.percent()` returns NaN.
- As a result, `tween.progress()` returns NaN`.
- As a result, `tween.duration().mul_f32(1.0 - tween.progress())` panics.

I feel like `Delay::progress()` should yield `1.0` for a 0-duration timer, but that would require special-casing on that.

**Comment by SUPERCILEX** [comment]
If that's the case, then this will almost certainly be fixed by https://github.com/djeedai/bevy_tweening/pull/38.

Sitenote: https://github.com/djeedai/bevy_tweening/pull/39 is probably going to get reverted since we're rewriting tracks and sequences.

**Comment by SUPERCILEX** [comment]
Nevermind, not fixed by https://github.com/djeedai/bevy_tweening/pull/38 because progress is still implemented the same way.

Though as mentioned, tick needs to be rewritten anyway to not use progress so this will go away.

**Comment by SUPERCILEX** [comment]
Note to self: write a test for this when rewriting sequences.

**Comment by Gyrobifastigium** [comment]
I don't know if this should go in a separate issue, but somehow in my game where I'm using a fork of `bevy_tweening` v0.4 with #39 applied, I just got a panic on the line `delta -= tween_remaining`. That shouldn't be possible unless some invariant in the tween API (between `duration()`, `progress()`, and `tick()`) is broken -- maybe as a result of floating point / rounding error.

As a workaround, I'm changing the line to `delta = delta.saturating_sub(tween_remaining)` in my fork for now.

**Comment by djeedai** [comment]
Interesting. What's the panic about exactly? Is `delta` becoming negative?

**Comment by Gyrobifastigium** [comment]
Yes, it is.

**Comment by shuoli84** [comment]
In my case, it is not rare, I hit by the panic each time run 
```
RUST_BACKTRACE=1 cargo run --example menu --features="bevy/bevy_winit"
```

**Comment by shuoli84** [comment]
A work around, set start_time_ms to a small value, e.g
```
    let mut start_time_ms = 10;
```

**Comment by benfrankel** [comment]
> In my case, it is not rare, I hit by the panic each time run
> 
> ```
> RUST_BACKTRACE=1 cargo run --example menu --features="bevy/bevy_winit"
> ```

I assume you're referring to the  "can not convert float seconds to Duration: value is negative" panic (original panic mentioned in this issue, guaranteed to occur in the menu example), and not the "overflow when subtracting durations" panic (mentioned in https://github.com/djeedai/bevy_tweening/issues/41#issuecomment-1209248797, occurs rarely in other code).

**Comment by shuoli84** [comment]
@benfrankel ah, yeah, different panic, "'can not convert float seconds to Duration: value is either too big or NaN'"

**Comment by djeedai** [comment]
> The Delay tween in the example has a 0-duration self.timer, so self.timer.percent() returns NaN.

Actually I think a `Delay` with a 0 duration makes no sense. I'll fix that to panic because creating such an object is most likely never what a user wants to do.

**Comment by djeedai** [comment]
I'm closing this issue because the `menu` example one is fixed. I believe the rare issue of @Gyrobifastigium might also be fixed, but since it's in a fork we can't really officially support it anyway. Please reopen if there's still an issue with the `menu` example, or open a different issue if something else. Thanks!
