### ISSUE TITLE
Repeat broken after first iteration

### ISSUE THREAD

**Issue by djeedai** [djeedai/bevy_tweening#42]
Run any example (except `menu` currently broken due to #41) : the color animation goes from red to blue smoothly during the first loop, then from the second loop ping-pongs between full red and full blue without any interpolation.

@SUPERCILEX this is probably due to a bug in #19.

This is blocking #34

**Comment by SUPERCILEX** [comment]
This isn't an issue in https://github.com/djeedai/bevy_tweening/pull/38 so let's try to get that through. Probs one of the things I said would be broken in the intermediary, but lemme try and find the bug real quick to confirm.

**Comment by SUPERCILEX** [comment]
Yeah, it's because progress is no longer bound to the 0,1 range and instead keeps increasing forever.
