### ISSUE TITLE
[Support?] How to animate complex shapes involving modifying a path, position, and rotation with multiple steps?

### ISSUE THREAD

**Issue by enaut** [djeedai/bevy_tweening#49]
Hey,

I want to create a turtlegraphics clone in bevy. So far I achieved the basic functionality:

https://user-images.githubusercontent.com/290005/186853826-97c6a175-39a0-4dfc-8357-e08811e18a8a.mp4

I did so by one line/circle etc each being one bundle with an animator...

Now I would like to make this form filled: like here https://github.com/sunjay/turtle/blob/master/docs/assets/images/examples/ferris.gif

But to fill that all the lines need to be in one bundle I think. Of course I could create a rather complicated lens that draws that bundle but the lerping would break because all the steps in the middle would be faster than at the beginning or the end...

I'm not sure if I found all the relevant documentation so I might miss something obvious. However I'd very much appreciate some hints on how such a thing could be achieved.

Thank you!

**Comment by enaut** [comment]
Hey,
I went ahead and built that "rather complicated lens" that works however I'm still unsure, whether this is a good way to do that. Would you be so kind to briefly look into this (~ 150 LOC)? [https://github.com/enaut/animating_filled_shape/blob/main/src/main.rs](https://github.com/enaut/animating_filled_shape/blob/main/src/main.rs)

I'd like to know if there is a better way to carry around the animation steps that already have been done instead of cloning them? Also the generation of the tween sequence seems to be rather prone to errors, might there be an easier way?
If you don't consider this request worth your time just close the issue...

**Comment by djeedai** [comment]
Sorry I was busy with the Jam. Essentially we're blocked here by the path API being a builder style and not allowing paths to be modified after they were created, which any animation system would find problematic to animate. So I don't think there's a better way than what you did @enaut

**Comment by enaut** [comment]
No worries, and thank you for your time and comment!
