### ISSUE TITLE
Multiply tweens to a single entity

### ISSUE THREAD

**Issue by Shatur** [djeedai/bevy_tweening#7]
Is it possible to apply multiply tweens to a single entity? Like `TransformPositionLens` + `TransformRotateYLens`. Or should I create a custom lens in this case?

**Comment by djeedai** [comment]
You can wrap those in a [`Tracks`](https://docs.rs/bevy_tweening/latest/bevy_tweening/struct.Tracks.html), if they're of the same duration. Even if they're not, the `Tracks` duration will be the duration of the longest of the two (or more) tweenables it wraps. The only issue here is that `Tracks` isn't loopable at the moment, only `Tween` is, so if you need looping you'll have to create a custom lens. I'd like to add looping to `Tracks` and `Sequence` in a future release but I didn't have time yet.

**Comment by Shatur** [comment]
Thanks for the answer!
I will open a separate issue about looping in `Tracks` and `Sequence`.
