### ISSUE TITLE
Custom lens not working

### ISSUE THREAD

**Issue by Cataykus** [djeedai/bevy_tweening#80]
Hi, i was trying to implement simple custom lens for animating my ui image alpha, but it doesn't work, am i doing something wrong ?

```rust
struct ImageOpacityLens {
    start: f32,
    end: f32,
}

impl Lens<BackgroundColor> for ImageOpacityLens {
    fn lerp(&mut self, target: &mut BackgroundColor, ratio: f32) {
        let interpolated_value = self.start + (self.end - self.start) * ratio;
        target.0.set_a(interpolated_value);
    }
}
```

```rust
let tween = Tween::new(
        EaseFunction::QuadraticInOut,
        Duration::from_secs(2),
        ImageOpacityLens {
            start: 0.0,
            end: 1.0,
        },
    )
    .with_repeat_count(RepeatCount::Finite(2))
    .with_repeat_strategy(RepeatStrategy::MirroredRepeat);

commands.spawn((
        ImageBundle {
            style: Style {
                margin: UiRect::all(Val::Auto),
                size: Size::new(Val::Px(300.0), Val::Auto),
                ..default()
            },
            image: UiImage(icon),
            ..default()
        },
        Animator::new(tween),
    ));
```

**Comment by djeedai** [comment]
Did you follow the steps in the README?

> Then, in addition, the system `component_animator_system::<CustomComponent>` needs to be added to the application. This system will extract each frame all CustomComponent instances with an Animator<CustomComponent> on the same entity, and animate the component via its animator.

`BackgroundColor` is not animated by default since there's no built-in lens for it.

**Comment by Cataykus** [comment]
Im so blind, after i add `component_animator_system::<BackgroundColor>` system all work fine, thanks

**Comment by djeedai** [comment]
Ah no worry, it's probably not clear enough then. Where would you have expected to find that info? I think I didn't find it in the docs anywhere, so that's probably one thing to fix already.

**Comment by paul-hansen** [comment]
Just ran into this myself, also wanting to animate bevy::ui::BackgroundColor. Since this was fresh in my mind I figured it might be helpful to say where I was looking for it:

- The example here: https://docs.rs/bevy_tweening/0.6.0/bevy_tweening/lens/trait.Lens.html#example
- In the readme here: https://github.com/djeedai/bevy_tweening#custom-lens
