### ISSUE TITLE
ColorMaterialColorLens bug

### ISSUE THREAD

**Issue by IvoteSligte** [djeedai/bevy_tweening#81]
`bevy::prelude::ColorMaterial` does not implement` bevy::prelude::Component`, which breaks `ColorMaterialColorLens`.

Full error message:
> error[E0277]: the trait bound `bevy::prelude::ColorMaterial: bevy::prelude::Component` is not satisfied
>      --> src\main.rs:265:44
>       |
>   265 |                 commands.entity(e2).insert(Animator::new(Tween::new(
>       |                                            ^^^^^^^^ the trait `bevy::prelude::Component` is not implemented for `bevy::prelude::ColorMaterial`
>       |
>       = help: the following other types implement trait `bevy::prelude::Component`:
>                 AdditionalMassProperties
>                 AlphaMode
>                 AnimationPlayer
>                 Animator<T>
>                 AssetAnimator<T>
>                 BackgroundColor
>                 Ball
>                 BloomSettings
>               and 120 others
>   note: required by a bound in `Animator`
>      --> {DIRECTORY}\bevy_tweening-0.6.0\src\lib.rs:408:24
>       |
>   408 | pub struct Animator<T: Component> {
>       |                        ^^^^^^^^^ required by this bound in `Animator`

**Comment by djeedai** [comment]
Thanks for the bug report. Yes it's a regression, it seems that `ColorMaterial` changed and so I'm not sure how to handle it now as it's neither a `Component` nor a `Resource`. In fact I'm not even sure how it's supposed to be modified even manually anymore. This needs a bit of investigation; suggestions welcome.

**Comment by IvoteSligte** [comment]
Currently the `ColorMaterial` is wrapped in a `Handle<T>`, which requires`ResMut<Assets<ColorMaterial>>` to be modified. The Handle<ColorMaterial> is basically the key to the ColorMaterial assets.

This is how `ColorMaterial`s are changed now:
> fn change_colors(
>     query: Query<&Handle<ColorMaterial>>,
>     mut materials: ResMut<Assets<ColorMaterial>>,
> ) {
>     for handle in query.iter() {
>         let color = &mut materials.get_mut(handle).unwrap().color;
>         color.set_a(color.a() * 0.99);
>     }
> }

Frankly I do not see a way to combine this with the current `Lens` trait as you need a system that receives `ResMut<Assets<ColorMaterial>>`. Perhaps a variation on `Lens` that takes a resource (instead of a mutable reference to a component) is in order?

**Comment by djeedai** [comment]
Wait no sorry `ColorMaterial` is an `Asset` so it's using the `AssetAnimator<T: Asset>` animator. See the [`colormaterial_color.rs`](https://github.com/djeedai/bevy_tweening/blob/main/examples/colormaterial_color.rs) example. There's no bug here, everything works as expected. And lenses do not care about `Asset` vs. `Component`, only the animator does.

**Comment by djeedai** [comment]
My guess is you tried to add an `Animator<ColorMaterial>` instead of an `AssetAnimator<ColorMaterial>`.

**Comment by IvoteSligte** [comment]
I did in fact try to do that, my apologies.

**Comment by djeedai** [comment]
Nothing to apologize about. This is one more reminder that this API is not user friendly, and I should try to consolidate and have a single `Animator` instead.

**Comment by djeedai** [comment]
Closing as user error. Please feel free to reopen of there's still an issue.
