### ISSUE TITLE
Avoid unnecessary change detection resulting from component lens

### ISSUE THREAD

**Issue by bonsairobo** [djeedai/bevy_tweening#91]
Right now the `Lens` trait's `lerp` method takes `&mut T` for `T: Component`, but it should only need `Mut<T>`.

The system invokes `DerefMut` so we have no chance to avoid change detection in a custom lens:

https://github.com/djeedai/bevy_tweening/blob/3c6b10e8b8745935e0bd25990924f977a1a6fb33/src/plugin.rs#L87

Specifically, I have a custom lens that acts like a discrete switch that changes from one value to another at a specific `ratio`. This would only require a single `DerefMut`, but in fact it happens every frame that the `Animator` is running.

**Comment by bonsairobo** [comment]
A workaround is to manually observe `animator.tweenable().progress()` and perform the component mutation.

**Comment by djeedai** [comment]
@bonsairobo better late than never ;) this should work now, by mean of `Targetable<T>` which is really the same as `Mut<T>`, being passed to `Lens::lerp()`.

**Comment by bonsairobo** [comment]
@djeedai Thanks! I'll give it a try when I jump back into my project.
